apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "candidate_id=904976121950"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 80
    targetPort: 80
  selector:
    app: vote
